name: BulundIndia workflow
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Get the version
        id: vars
        run: echo ::set-output name=tag::$(echo ${GITHUB_REF:4})
      - name: Build the tagged Docker image
        run: docker build . --file Dockerfile --tag npsoni/tweepy:${{steps.vars.outputs.tag}}
      - name: Push the tagged Docker image
        run: docker push npsoni/tweepy:${{steps.vars.outputs.tag}}